package db_hib;

// Generated Dec 1, 2012 6:46:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Data generated by hbm2java
 */
public class Data implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6730486172280261828L;
	private Long id;
	private long donor;
	private long recv;
	private float amount;
	private long testimonialId;
	private Date date;

	public Data() {
	}

	public Data(long donor, long recv, float amount, long testimonialId, Date date) {
		this.donor = donor;
		this.recv = recv;
		this.amount = amount;
		this.testimonialId = testimonialId;
		this.date = date;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getDonor() {
		return this.donor;
	}

	public void setDonor(long donor) {
		this.donor = donor;
	}

	public long getRecv() {
		return this.recv;
	}

	public void setRecv(long recv) {
		this.recv = recv;
	}

	public float getAmount() {
		return this.amount;
	}

	public void setAmount(float amount) {
		this.amount = amount;
	}

	public long getTestimonialId() {
		return this.testimonialId;
	}

	public void setTestimonialId(long testimonialId) {
		this.testimonialId = testimonialId;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
