package db_hib;

// Generated Dec 1, 2012 3:05:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Entity generated by hbm2java
 */
public class Entity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8692357661016143496L;
	private long id;
	private String name;
	private long score;

	public Entity() {
	}

	public Entity(long id, long score) {
		this.id = id;
		this.score = score;
	}

	public Entity(long id, String name, long score) {
		this.id = id;
		this.name = name;
		this.score = score;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public long getScore() {
		return this.score;
	}

	public void setScore(long score) {
		this.score = score;
	}

}
