package db_hib;

// Generated Dec 1, 2012 6:46:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * Meta generated by hbm2java
 */
public class Meta implements java.io.Serializable {

	private long id;
	private String name;
	private long score;

	public Meta() {
	}

	public Meta(long id, long score) {
		this.id = id;
		this.score = score;
	}

	public Meta(long id, String name, long score) {
		this.id = id;
		this.name = name;
		this.score = score;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public long getScore() {
		return this.score;
	}

	public void setScore(long score) {
		this.score = score;
	}

}
