package db_hib;

// Generated Dec 1, 2012 3:05:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * Testimonial generated by hbm2java
 */
public class Testimonial implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2402659737978880843L;
	private long id;
	private byte[] proof;
	private long entityId;

	public Testimonial() {
	}

	public Testimonial(long id, byte[] proof, long entityId) {
		this.id = id;
		this.proof = proof;
		this.entityId = entityId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public byte[] getProof() {
		return this.proof;
	}

	public void setProof(byte[] proof) {
		this.proof = proof;
	}

	public long getEntityId() {
		return this.entityId;
	}

	public void setEntityId(long entityId) {
		this.entityId = entityId;
	}

}
