package db_hib;

// Generated Dec 1, 2012 6:46:18 PM by Hibernate Tools 3.4.0.CR1

/**
 * Testimonial generated by hbm2java
 */
public class Testimonial implements java.io.Serializable {

	private long id;
	private byte[] proof;
	private long entityId;

	public Testimonial() {
	}

	public Testimonial(long id, byte[] proof, long entityId) {
		this.id = id;
		this.proof = proof;
		this.entityId = entityId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getProof() {
		return this.proof.toString();
	}

	public void setProof(byte[] proof) {
		this.proof = proof;
	}

	public long getEntityId() {
		return this.entityId;
	}

	public void setEntityId(long entityId) {
		this.entityId = entityId;
	}

}
